# Copyright (c) 2019 Vitasystems GmbH and Jake Smolka (Hannover Medical School).
#
# This file is part of Project EHRbase
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    schemas: ehr

cache:
  config: '/ehcache.xml'
  enabled: true

system:
  allow-template-overwrite: false

logging:
  level:
    org.springframework: INFO
    de.vitasystems: TRACE
    com.ethercis: DEBUG
    org.jooq: INFO
    net.sf.ehcache: TRACE