name: Java CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
    - release/*

  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build EHRbase .jar
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Cache Maven Dependencies
      uses: actions/cache@v1.0.2
      id: cache-maven
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@0.0.1

    - name: Start PostgreSQL DB container
      run: |
        docker run --name ehrdb -e POSTGRES_USER=postgres \
                                -e POSTGRES_PASSWORD=postgres \
                                -d -p 5432:5432 ehrbaseorg/ehrbase-database-docker:11.5

    - name: Build EHRbase Server with Maven
      run: mvn package

    - name: Cache EHRbase .jar Artefact
      uses: actions/cache@v1.0.2
      id: cache-jar
      with:
        path: application/target
        key: ${{ runner.os }}-jar-
        restore-keys: |
          ${{ runner.os }}-jar-

    ## NOTE: cache is faster than this! | use cache!
    # - name: Upload EHRbase .jar
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: application-0.9.0.jar
    #     path: application/target/application-0.9.0.jar



  test:
    name: Test EHRbase Services
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@0.0.1

    - name: Start PostgreSQL DB container
      run: |
        docker run --name ehrdb -e POSTGRES_USER=postgres \
                                -e POSTGRES_PASSWORD=postgres \
                                -d -p 5432:5432 ehrbaseorg/ehrbase-database-docker:11.5

    - name: Cache Python Dependencies
      uses: actions/cache@v1
      id: cache-python
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python/Test Dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        cd tests/
        pip3 install -r requirements.txt
        robot --version

    ## NOTE: download is slower than cache | use cache!
    # - name: Download EHRbase .jar
    #   uses: actions/download-artifact@v1
    #   with:
    #     name: application-0.9.0.jar
    #     path: application/target

    - name: Restore Cache EHRbase .jar
      uses: actions/cache@v1.0.2
      id: cache-jar
      with:
        path: application/target
        key: ${{ runner.os }}-jar-
        restore-keys: |
          ${{ runner.os }}-jar-

    - name: Start EHRbase Server
      run: |
        ls -la
        java -jar application/target/application-0.9.0.jar > log &
        grep -m 1 "Started EhrBase in" <(tail -f log)
        echo "READY FOR TEST"

    - name: Run Robot Tests
      run: |
        cd tests/
        robot -i circleci -d results -L TRACE robot/

    - name: Upload Test Results
      uses: actions/upload-artifact@master
      with:
        name: results
        path: tests/results
