name: Java CI

on:
  push:

  pull_request:
    branches:
    - master
    - develop

jobs:
  # build:
  #   name: Build EHRbase .jar
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Checkout Code
  #     uses: actions/checkout@v2

  #   - name: Cache Maven Dependencies
  #     uses: actions/cache@v1
  #     id: cache-maven
  #     with:
  #       path: ~/.m2/repository
  #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #       restore-keys: |
  #         ${{ runner.os }}-maven-

  #   - name: Set Up Java JDK 11
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 11

  #   - name: Start PostgreSQL DB container
  #     run: |
  #       docker run --name ehrdb -e POSTGRES_USER=postgres \
  #                               -e POSTGRES_PASSWORD=postgres \
  #                               -d -p 5432:5432 ehrbaseorg/ehrbase-database-docker:11.5

  #   - name: Build EHRbase Server with Maven
  #     run: mvn package

  #   - name: Cache EHRbase .jar Artefact
  #     uses: actions/cache@v1
  #     id: cache-jar
  #     with:
  #       path: application/target
  #       key: ${{ runner.os }}-jar-
  #       restore-keys: |
  #         ${{ runner.os }}-jar-

  #   ## NOTE: cache is faster than this! | use cache!
  #   # - name: Upload EHRbase .jar
  #   #   uses: actions/upload-artifact@master
  #   #   with:
  #   #     name: application-0.9.0.jar
  #   #     path: application/target/application-0.9.0.jar



  test:
    name: TEST EHRBASE SERVICES
    runs-on: ubuntu-latest
    # needs: build
    strategy:
      matrix:
        python-version: [3.8]

    steps:

    - name: CHECKOUT CODE
      uses: actions/checkout@v2


    - name: RESTORE CACHE EHRBASE .jar
      uses: actions/cache@v1
      id: cache-jar
      with:
        path: application/target
        key: ${{ runner.os }}-jar-
        restore-keys: |
          ${{ runner.os }}-jar-


    - name: SET UP PYTHON ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1

    - name: INSTALL TEST DEPENDENCIES
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        cd tests/
        pip install -r requirements.txt


    - name: CACHE PYTHON DEPENDENCIES
      uses: actions/cache@v1
      id: cache-python
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    ## NOTE: download is slower than cache | use cache!
    # - name: Download EHRbase .jar
    #   uses: actions/download-artifact@v1
    #   with:
    #     name: application-0.9.0.jar
    #     path: application/target


    - name: RUN ROBOT TESTS
      run: |
        cd tests/
        robot -i circleci -d results -L TRACE robot/


    - name: UPLOAD TEST RESULTS
      uses: actions/upload-artifact@master
      with:
        name: results
        path: tests/results

    





# oooooooooo.        .o.         .oooooo.   oooo    oooo ooooo     ooo ooooooooo.
# `888'   `Y8b      .888.       d8P'  `Y8b  `888   .8P'  `888'     `8' `888   `Y88.
#  888     888     .8"888.     888           888  d8'     888       8   888   .d88'
#  888oooo888'    .8' `888.    888           88888[       888       8   888ooo88P'
#  888    `88b   .88ooo8888.   888           888`88b.     888       8   888
#  888    .88P  .8'     `888.  `88b    ooo   888  `88b.   `88.    .8'   888
# o888bood8P'  o88o     o8888o  `Y8bood8P'  o888o  o888o    `YbodP'    o888o
#
# [ BACKUP ]

    # steps:

    # - name: START POSTGRESQL DB
    #   run: |
    #     docker run --name ehrdb -e POSTGRES_USER=postgres \
    #                             -e POSTGRES_PASSWORD=postgres \
    #                             -d -p 5432:5432 ehrbaseorg/ehrbase-database-docker:11.5

    # - name: RESTORE CACHE EHRBASE .jar
    #   uses: actions/cache@v1
    #   id: cache-jar
    #   with:
    #     path: application/target
    #     key: ${{ runner.os }}-jar-
    #     restore-keys: |
    #       ${{ runner.os }}-jar-
    
    # - name: START EHRBASE SERVER
    #   run: |
    #     ls -la
    #     java -jar ../application/target/application-*.jar --cache.enabled=false > log &
    #     sleep 20
    #     echo "READY FOR TEST"

    # # NOTE: Use this step for live debugging on CI runner
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v1